export const tokenMock =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlQGVtYWlsLmNvbSIsInVzZXIiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNjUxMDAxNywiZXhwIjoxNzE2NTE3MjE3fQ.qIgJqq16vB-zVr9xRg2W_Xt4WRUdfd06veoY_piAQjY';
